apiVersion: v1
kind: Service
metadata:
  name: aspnetcore-invservice
  labels:
    app: aspnetcoreinvapp
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: aspnetcoreinvapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcoreinvapp-v1
spec:
  selector:

    matchLabels:

      app: aspnetcoreinvapp
  replicas: 1
  template:
    metadata:
      labels:
        app: aspnetcoreinvapp
        version: v1
    spec:
      containers:
      - name: aspnetcoreinvapp
        image: eswaribala/intelmay2022repo:v1
        
        ports:
        - containerPort: 80
        env:

            - name: ASPNETCORE_ENVIRONMENT

              value: DEVELOPMENT

            - name: SQLSERVER_CONNECTIONSTRING

              value: "Server=Server=host.docker.internal,1433;Database=IntelInventoryDB;User ID=sa;Password=Vignesh@95;MultipleActiveResultSets=true"