// <auto-generated />
using CQRSNET6Demo.Models.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CQRSNET6Demo.Migrations
{
    [DbContext(typeof(CustomerSQLiteDatabaseContext))]
    [Migration("20220613164506_sqlite-migration")]
    partial class sqlitemigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("CQRSNET6Demo.Models.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("MobileNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CQRSNET6Demo.Models.Invoice", b =>
                {
                    b.Property<long>("InvoiceNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DOI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceNo");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("CQRSNET6Demo.Models.Invoice", b =>
                {
                    b.HasOne("CQRSNET6Demo.Models.Customer", "Customer")
                        .WithMany("InvoiceList")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CQRSNET6Demo.Models.Customer", b =>
                {
                    b.Navigation("InvoiceList");
                });
#pragma warning restore 612, 618
        }
    }
}
